-- ----------------------------------------------------
--  用户表
-- ----------------------------------------------------
DROP TABLE IF EXISTS SYSDBA.SYS_USER;
CREATE TABLE SYSDBA.SYS_USER
(
    ID integer NOT NULL AUTO_INCREMENT, 
	NAME character varying(50) NOT NULL,
    PASSWORD character varying(100) NOT NULL,
    SALT character varying(40) ,
	MOBILE character varying(40) ,	
    EMAIL character varying(100) ,
    TOOL_USE_NUM integer , 
	CREATE_BY character varying(100) ,
    CREATE_TIME timestamp without time zone ,    
    LAST_UPDATE_BY character varying(40) ,
    LAST_UPDATE_TIME timestamp without time zone ,
	DEL_FLAG smallint DEFAULT 0 ,
    CONSTRAINT SYS_USER_UK UNIQUE ("NAME"), 
    CONSTRAINT SYS_USER_PKEY PRIMARY KEY (ID)
) AUTO_INCREMENT = 0 NOLOGGING
 BINLOG ON ;
--Table Comment
COMMENT ON TABLE SYSDBA.SYS_USER IS '用户表';
COMMENT ON COLUMN SYSDBA.SYS_USER.ID IS 'ID';
COMMENT ON COLUMN SYSDBA.SYS_USER."NAME" IS '用户名';
COMMENT ON COLUMN SYSDBA.SYS_USER."PASSWORD" IS '密码';
COMMENT ON COLUMN SYSDBA.SYS_USER.SALT IS '盐';
COMMENT ON COLUMN SYSDBA.SYS_USER.MOBILE IS '手机号';
COMMENT ON COLUMN SYSDBA.SYS_USER.EMAIL IS '邮箱';
COMMENT ON COLUMN SYSDBA.SYS_USER.TOOL_USE_NUM IS '工具剩余使用次数 999 无限制';
COMMENT ON COLUMN SYSDBA.SYS_USER.CREATE_BY IS '创建人';
COMMENT ON COLUMN SYSDBA.SYS_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYSDBA.SYS_USER.LAST_UPDATE_BY IS '更新人';
COMMENT ON COLUMN SYSDBA.SYS_USER.LAST_UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYSDBA.SYS_USER.DEL_FLAG IS '是否删除 0：正常 1：已删除';

INSERT INTO SYSDBA.SYS_USER
(ID, "NAME", "PASSWORD", SALT, MOBILE, EMAIL, TOOL_USE_NUM, CREATE_BY, CREATE_TIME, LAST_UPDATE_BY, LAST_UPDATE_TIME, DEL_FLAG)
VALUES(1, 'admin', '4db0eda317e891f63035d5bc8fbe801a', 'b6da1efbcf4c4f9fb5d7', '16666666666', NULL, 0, 'admin', '2021-01-01 00:00:00.000', 'admin', '2021-01-01 00:00:00.000', 0);

-- ----------------------------------------------------
--  角色表
-- ----------------------------------------------------
DROP TABLE IF EXISTS SYSDBA.SYS_ROLE;
CREATE TABLE SYSDBA.SYS_ROLE
(
    ID integer NOT NULL AUTO_INCREMENT,
    "NAME" character varying(50) NOT NULL,
    REMARK character varying(2000) ,
    CREATE_BY character varying(100) ,
    CREATE_TIME timestamp without time zone ,
    LAST_UPDATE_BY character varying(100) ,
    LAST_UPDATE_TIME timestamp without time zone ,
    DEL_FLAG smallint DEFAULT 0 , 
    CONSTRAINT ROLE_PK PRIMARY KEY (ID)
) AUTO_INCREMENT = 0   NOLOGGING
 BINLOG ON ;
--Table Comment
COMMENT ON TABLE SYSDBA.SYS_ROLE IS '角色表';
COMMENT ON COLUMN SYSDBA.SYS_ROLE.ID IS 'ID';
COMMENT ON COLUMN SYSDBA.SYS_ROLE."NAME" IS '角色名';
COMMENT ON COLUMN SYSDBA.SYS_ROLE.REMARK IS '备注';
COMMENT ON COLUMN SYSDBA.SYS_ROLE.CREATE_BY IS '创建人';
COMMENT ON COLUMN SYSDBA.SYS_ROLE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYSDBA.SYS_ROLE.LAST_UPDATE_BY IS '最后更新人';
COMMENT ON COLUMN SYSDBA.SYS_ROLE.LAST_UPDATE_TIME IS '最后更新时间';
COMMENT ON COLUMN SYSDBA.SYS_ROLE.DEL_FLAG IS '是否删除 0：正常 1：已删除';

INSERT INTO SYSDBA.SYS_ROLE ("NAME",REMARK,CREATE_BY,CREATE_TIME,LAST_UPDATE_BY,LAST_UPDATE_TIME,DEL_FLAG) VALUES 
('管理员','拥有所有菜单权限','admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,('普通用户','可以使用迁移功能','admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0);


-- ----------------------------------------------------
--  用户与角色对应关系
-- ----------------------------------------------------
DROP TABLE IF EXISTS SYSDBA.SYS_USER_ROLE;
CREATE TABLE SYSDBA.SYS_USER_ROLE
(
    ID integer NOT NULL AUTO_INCREMENT,
    USER_ID integer NOT NULL,
    ROLE_ID integer NOT NULL,
    CREATE_BY character varying(100) ,
    CREATE_TIME timestamp without time zone ,
    LAST_UPDATE_BY character varying(100) ,
    LAST_UPDATE_TIME timestamp without time zone ,
    DEL_FLAG tinyint DEFAULT 0 , 
    CONSTRAINT USER_ROLE_PK PRIMARY KEY (ID)
) AUTO_INCREMENT = 0 NOLOGGING
 BINLOG ON ;
--Table Comment
COMMENT ON TABLE SYSDBA.SYS_USER_ROLE IS '用户与角色对应关系';
COMMENT ON COLUMN SYSDBA.SYS_USER_ROLE.ID IS 'ID';
COMMENT ON COLUMN SYSDBA.SYS_USER_ROLE.USER_ID IS '用户ID';
COMMENT ON COLUMN SYSDBA.SYS_USER_ROLE.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYSDBA.SYS_USER_ROLE.CREATE_BY IS '创建人';
COMMENT ON COLUMN SYSDBA.SYS_USER_ROLE.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYSDBA.SYS_USER_ROLE.LAST_UPDATE_BY IS '更新人';
COMMENT ON COLUMN SYSDBA.SYS_USER_ROLE.LAST_UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYSDBA.SYS_USER_ROLE.DEL_FLAG IS '是否删除 0：正常 1：已删除';

INSERT INTO SYSDBA.SYS_USER_ROLE (USER_ID,ROLE_ID,CREATE_BY,CREATE_TIME,LAST_UPDATE_BY,LAST_UPDATE_TIME,DEL_FLAG) VALUES 
(1,1,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0);

-- ----------------------------------------------------
--  菜单表
-- ----------------------------------------------------
DROP TABLE IF EXISTS SYSDBA.SYS_MENU;
CREATE TABLE SYSDBA.SYS_MENU
(
    ID integer NOT NULL AUTO_INCREMENT,
    NAME character varying(50) NOT NULL,
    PARENT_ID integer DEFAULT 0 NOT NULL,
    URL character varying(500) NOT NULL,
    TYPE smallint ,
    ICON character varying(100) ,
    ORDER_NUM smallint ,
    CREATE_BY character varying(100) ,
    CREATE_TIME timestamp without time zone ,
    LAST_UPDATE_BY character varying(100) ,
    LAST_UPDATE_TIME timestamp without time zone ,
    DEL_FLAG smallint DEFAULT 0 , 
    CONSTRAINT MENU_PK PRIMARY KEY (ID)
) AUTO_INCREMENT = 0  NOLOGGING
 BINLOG ON ;
--注释
COMMENT ON TABLE SYSDBA.SYS_MENU IS '菜单表';
COMMENT ON COLUMN SYSDBA.SYS_MENU.ID IS 'ID';
COMMENT ON COLUMN SYSDBA.SYS_MENU."NAME" IS '菜单名称';
COMMENT ON COLUMN SYSDBA.SYS_MENU.PARENT_ID IS '父菜单ID，一级菜单为0';
COMMENT ON COLUMN SYSDBA.SYS_MENU.URL IS '菜单路由地址';
COMMENT ON COLUMN SYSDBA.SYS_MENU."TYPE" IS '类型   0：目录   1：菜单';
COMMENT ON COLUMN SYSDBA.SYS_MENU.ICON IS '菜单图标';
COMMENT ON COLUMN SYSDBA.SYS_MENU.ORDER_NUM IS '排序';
COMMENT ON COLUMN SYSDBA.SYS_MENU.CREATE_BY IS '创建人';
COMMENT ON COLUMN SYSDBA.SYS_MENU.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYSDBA.SYS_MENU.LAST_UPDATE_BY IS '更新人';
COMMENT ON COLUMN SYSDBA.SYS_MENU.LAST_UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYSDBA.SYS_MENU.DEL_FLAG IS '是否删除 0：正常 1：已删除';

INSERT INTO SYSDBA.SYS_MENU ("NAME",PARENT_ID,URL,"TYPE",ICON,ORDER_NUM,CREATE_BY,CREATE_TIME,LAST_UPDATE_BY,LAST_UPDATE_TIME,DEL_FLAG) VALUES 
('数据迁移',0,'/DataMigration/DataMigration',1,'fa fa-exchange',1,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,('迁移历史',0,'/MigrationHistory/MigrationHistory',1,'fa fa-history',2,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,('系统设置',0,'/systemSetting',0,'fa fa-cog',3,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,('用户管理',3,'/SystemSetting/UserManagement',1,'fa fa-user-circle-o',1,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,('角色管理',3,'/SystemSetting/RoleManagement',1,'el-icon-view',2,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0);

-- ----------------------------------------------------
--  角色与菜单关系表
-- ----------------------------------------------------
DROP TABLE IF EXISTS SYSDBA.SYS_ROLE_MENU;
CREATE TABLE SYSDBA.SYS_ROLE_MENU
(
    ID integer NOT NULL AUTO_INCREMENT,
    ROLE_ID integer NOT NULL,
    MENU_ID integer NOT NULL,
    CREATE_BY character varying(100) ,
    CREATE_TIME timestamp without time zone ,
    LAST_UPDATE_BY character varying(100) ,
    LAST_UPDATE_TIME timestamp without time zone ,
    DEL_FLAG smallint DEFAULT 0 , 
    CONSTRAINT ROLE_MENU_PK PRIMARY KEY (ID)
) AUTO_INCREMENT = 0  NOLOGGING
 BINLOG ON ;
--Table Comment
COMMENT ON TABLE SYSDBA.SYS_ROLE_MENU IS '角色与菜单关系表';
COMMENT ON COLUMN SYSDBA.SYS_ROLE_MENU.ID IS 'ID';
COMMENT ON COLUMN SYSDBA.SYS_ROLE_MENU.ROLE_ID IS '角色ID';
COMMENT ON COLUMN SYSDBA.SYS_ROLE_MENU.MENU_ID IS '菜单ID';
COMMENT ON COLUMN SYSDBA.SYS_ROLE_MENU.CREATE_BY IS '创建人';
COMMENT ON COLUMN SYSDBA.SYS_ROLE_MENU.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYSDBA.SYS_ROLE_MENU.LAST_UPDATE_BY IS '更新人';
COMMENT ON COLUMN SYSDBA.SYS_ROLE_MENU.LAST_UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYSDBA.SYS_ROLE_MENU.DEL_FLAG IS '是否删除 0：正常 1：已删除';

INSERT INTO SYSDBA.SYS_ROLE_MENU (ROLE_ID,MENU_ID,CREATE_BY,CREATE_TIME,LAST_UPDATE_BY,LAST_UPDATE_TIME,DEL_FLAG) VALUES 
(1,1,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,(1,2,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,(1,3,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,(1,4,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,(1,5,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,(2,1,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0)
,(2,2,'admin','2021-01-01 00:00:00.000','admin','2021-01-01 00:00:00.000',0);


